replicaCount: 1

image:
  repository: registry-local:5000/admin/hola-mundo
  pullPolicy: IfNotPresent
  tag: latest

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: NodePort
  port: 3000
  nodePort: 30000

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources:
  limits:
    cpu: 500m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi

livenessProbe:
  httpGet:
    path: /hola-mundo/v1/healthcheck
    port: 3000
  initialDelaySeconds: 15
  periodSeconds: 60

readinessProbe:
  httpGet:
    path: /hola-mundo/v1/healthcheck
    port: 3000
  initialDelaySeconds: 5
  periodSeconds: 30

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

configmap:
  name: hola-mundo
  data:
    DATABASE_URL: postgres://postgres:mypassword1@db:5432/hola-mundo

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}
