apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: filebeat
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    filebeat.inputs:
      - type: container
        enabled: true
        paths:
          - /var/log/containers/*.log
        processors:
          - add_kubernetes_metadata:
              host: ${NODE_NAME}

    output.logstash:
      hosts: ["dev-elk-logstash01:5044"]

    setup.ilm.enabled: false
    setup.template.enabled: false
    logging.level: info
